#!/bin/bash

###########################
### CONFIGURATION START ###

#to use your default jre on your system use JAVA_BIN="java", or you can give the full path of java.
JAVA_BIN="java"

JAVA_OPTIONS="-client"

### CONFIGURATION END ###
#########################

PROGNAME=`basename $0`

## find java version in the default path
JAVA_VER=$($JAVA_BIN -version 2>&1 | grep version | cut -d\" -f 2-2 | cut -c 1-3)

find_java () {
    if [[ "$JAVA_VER" = "1.7" || "$JAVA_VER" = "1.8" || "$JAVA_VER" = "1.9" ]] ; then
        echo "Java version in the default path is: $JAVA_VER"
    else
        echo "Java version in the default path is: $JAVA_VER"
        echo "No Java compatible version detected"
	exit 0
     fi
}

## Check arquitecture
if [ "`uname -m`" = "x86_64" ]; then
	ARCHLIB=x86_64
elif [ "`uname -m`" = "armv7l" ]; then
	ARCHLIB=armv7l
else
	echo "Architecture not supported yet"
	exit 0
fi

echo "Architecture $ARCHLIB"

## find installed java version 
find_java 

cp=$(find "modules" -name "tris-voice-control*.jar" | sort | tail -1);
echo $cp

## start

$JAVA_BIN $JAVA_OPTIONS -Djava.library.path=./lib/$ARCHLIB -jar $cp
